---
- name: Copy basic wired network config
  ansible.builtin.copy:
    src: "{{ role_path }}/templates/20-wired.j2"
    dest: /etc/systemd/network/20-wired.network
    owner: root
    group: root
    mode: '0644'
  when: config_wired
  notify: Restart systemd-networkd

- name: Copy basic wireless network config
  ansible.builtin.template:
    src: "{{ role_path }}/templates/25-wireless.j2"
    dest: /etc/systemd/network/25-wireless.network
    owner: root
    group: root
    mode: '0644'
  when: config_wireless
  notify: Restart systemd-networkd

- name: Enable systemd-networkd & systemd-resolved
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
  with_items:
    - systemd-networkd
    - systemd-resolved
