# https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html
---
namespace: dandyrow
name: iac
version: 0.1.0
readme: README.md
authors:
  - Daniel Lowry (github.com/dandyrow)
description: Collection of tools for defining infrastructure as code.
license_file: LICENSE
tags:
  - infrastructureascode
  - linux
  - stow
  - infrastructure
repository: https://github.com/dandyrow/dandyrow.iac
documentation: https://dandyrow.github.io/dandyrow.iac
homepage: https://dandyrow.github.io/dandyrow.iac
issues: https://github.com/dandyrow/dandyrow.iac/issues
build_ignore:
  - .gitignore
