# https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html
---
namespace: dandyrow
name: linux
version: 2.3.0
readme: README.md
authors:
  - Daniel Lowry (github.com/dandyrow)
description: Collection of tools for defining infrastructure as code.
license_file: LICENSE
tags:
  - infrastructureascode
  - linux
  - stow
  - infrastructure
repository: https://github.com/dandyrow/dandyrow.linux
documentation: https://dandyrow.github.io/dandyrow.linux
homepage: https://dandyrow.github.io/dandyrow.linux
issues: https://github.com/dandyrow/dandyrow.linux/issues
build_ignore:
  - .gitignore
