---
galaxy_info:
  role_name: swapfile
  author: Daniel Lowry
  namespace: dandyrow
  description: Create & setup swapfile
  license: GPL-3.0-only
  min_ansible_version: "2.12"

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - "jammy"
        - "focal"
    - name: Debian
      version:
        - "bullseye"
        - "buster"

  galaxy_tags:
    - swap
    - linux

dependencies: []
