---
- name: Check for existance of /sys/firmware/efi/efivars
  ansible.builtin.stat:
    path: /sys/firmware/efi/efivars
  register: efivars_directory

- name: Fail if efi directory doesn't exist
  ansible.builtin.fail:
    msg: System isn't booted into UEFI mode
  when: not efivars_directory.stat.exists

- name: Ensure the ESP exists
  ansible.builtin.file:
    path: "{{ esp_path }}"
    owner: root
    group: root
    mode: '0755'
    state: directory
  become: true

- name: Install systemd-boot
  ansible.builtin.command:
    cmd: bootctl --esp-path={{ esp_path }} install
    creates: "{{ esp_path }}/EFI/systemd/systemd-bootx64.efi"
  become: true

- name: Enable auto updating of systemd boot
  ansible.builtin.service:
    name: systemd-boot-update
    enabled: "{{ auto_update }}"
  become: true

- name: Create loader directory in ESP
  ansible.builtin.file:
    path: "{{ esp_path }}/loader"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Copy loader config to loader directory
  ansible.builtin.template:
    src: "{{ role_path }}/templates/loader.j2"
    dest: "{{ esp_path }}/loader/loader.conf"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create entries directory in loader directory
  ansible.builtin.file:
    path: "{{ esp_path }}/loader/entries"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Get root partition
  ansible.builtin.shell: |
    set -e -o pipefail
    mount | grep 'on / ' | awk '{ print $1 }'
  register: root_partition
  changed_when: false

- name: Get root partition UUID using blkid as lsblk didn't work
  ansible.builtin.command: blkid -s UUID -o value {{ root_partition.stdout }}
  register: root_partition_uuid

- name: Copy loader entry to entries directory
  ansible.builtin.template:
    src: "{{ role_path }}/templates/entry.j2"
    dest: "{{ esp_path }}/loader/entries/{{ entry_title }}.conf"
    owner: root
    group: root
    mode: "0755"
  become: true
