---
argument_specs:
  main:
    short_description: Install and configure cloud-init
    description:
      - Install and configure cloud-init.
    author:
      - Daniel Lowry (github.com/dandyrow)
    options:
      create_default_user:
        description:
          - If true, cloud-init will create the default user when it runs.
          - Default user is defined by your distro's cloud-init package.
        type: bool
        default: true

      disable_root:
        description:
          - If true, ssh login as root will be disabled.
        type: bool
        default: true

      preserve_hostname:
        description:
          - If true, hostname will not be changed by cloud-init.
        type: bool
        default: false

      datasource_list:
        description:
          - List of datasources for cloud-init to query.
          - "List of datasources can be found here: \
            https://cloudinit.readthedocs.io/en/latest/reference/datasources.html"
