---
galaxy_info:
  role_name: cloud_init
  author: Daniel Lowry
  namespace: dandyrow
  description: >-
    Ansible role to install and configure cloud-init
  license: GPL-3.0-only
  min_ansible_version: "2.12"

  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Ubuntu
      versions:
        - "jammy"
        - "focal"
    - name: Debian
      version:
        - "bullseye"
        - "buster"

  galaxy_tags:
    - linux
    - cloud_init
    - proxmox
    - vmware
    - cloud

dependencies: []
