---
- name: Link local timezone file in /etc/localtime
  ansible.builtin.file:
    src: /usr/share/zoneinfo/{{ region }}/{{ city }}
    dest: /etc/localtime
    force: true
    state: link
  become: true

- name: Set the hardware clock to the current system time
  ansible.builtin.command:
    cmd: hwclock --systohc
    creates: /etc/adjtime
  when: >-
    ansible_virtualization_role is defined and
    ansible_virtualization_role == 'host'
  become: true
