---
- name: Include distro specific variables
  ansible.builtin.include_vars: "{{ role_path }}/vars/\
    {{ ansible_os_family }}.yml"

- name: Update apt cache on Debian based systems
  ansible.builtin.apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Ensure Network Manager is installed
  ansible.builtin.package:
    name:
      - "{{ networkmanager_package }}"
    state: present

- name: Ensure Network Manager is enabled
  ansible.builtin.service:
    name: NetworkManager
    enabled: true
